[2022-04-28 06:06:17,832] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__2005-01-01T00:00:00+00:00 [queued]>
[2022-04-28 06:06:17,875] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__2005-01-01T00:00:00+00:00 [queued]>
[2022-04-28 06:06:17,877] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 06:06:17,878] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-28 06:06:17,879] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 06:06:17,921] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): format_xl_to_csv_task> on 2005-01-01 00:00:00+00:00
[2022-04-28 06:06:17,932] {standard_task_runner.py:52} INFO - Started process 2015 to run task
[2022-04-28 06:06:17,940] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'format_xl_to_csv_task', 'scheduled__2005-01-01T00:00:00+00:00', '--job-id', '546', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmp8bc37_5i', '--error-file', '/tmp/tmplne3buk7']
[2022-04-28 06:06:17,944] {standard_task_runner.py:80} INFO - Job 546: Subtask format_xl_to_csv_task
[2022-04-28 06:06:18,343] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__2005-01-01T00:00:00+00:00 [running]> on host d4721d223bdd
[2022-04-28 06:06:18,679] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-28 06:06:18,873] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=format_xl_to_csv_task
AIRFLOW_CTX_EXECUTION_DATE=2005-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2005-01-01T00:00:00+00:00
[2022-04-28 06:06:24,236] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "pandas/_libs/lib.pyx", line 2305, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "N.A."

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 174, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 188, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ingest_to_gcs_dag.py", line 55, in format_xl_to_csv
    df.unemployment_rate = pd.to_numeric(df.unemployment_rate)
  File "/home/airflow/.local/lib/python3.7/site-packages/pandas/core/tools/numeric.py", line 184, in to_numeric
    values, set(), coerce_numeric=coerce_numeric
  File "pandas/_libs/lib.pyx", line 2347, in pandas._libs.lib.maybe_convert_numeric
ValueError: Unable to parse string "N.A." at position 1135
[2022-04-28 06:06:24,369] {taskinstance.py:1288} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcp_dag, task_id=format_xl_to_csv_task, execution_date=20050101T000000, start_date=20220428T060617, end_date=20220428T060624
[2022-04-28 06:06:24,509] {standard_task_runner.py:98} ERROR - Failed to execute job 546 for task format_xl_to_csv_task (Unable to parse string "N.A." at position 1135; 2015)
[2022-04-28 06:06:24,582] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-28 06:06:24,848] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-29 02:36:51,915] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__2005-01-01T00:00:00+00:00 [queued]>
[2022-04-29 02:36:51,976] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__2005-01-01T00:00:00+00:00 [queued]>
[2022-04-29 02:36:51,979] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 02:36:51,981] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-29 02:36:51,983] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 02:36:52,034] {taskinstance.py:1270} INFO - Executing <Task(PythonOperator): format_xl_to_csv_task> on 2005-01-01 00:00:00+00:00
[2022-04-29 02:36:52,046] {standard_task_runner.py:52} INFO - Started process 5606 to run task
[2022-04-29 02:36:52,058] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'format_xl_to_csv_task', 'scheduled__2005-01-01T00:00:00+00:00', '--job-id', '721', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpx1ut7o5p', '--error-file', '/tmp/tmpxslh11dh']
[2022-04-29 02:36:52,061] {standard_task_runner.py:80} INFO - Job 721: Subtask format_xl_to_csv_task
[2022-04-29 02:36:52,494] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__2005-01-01T00:00:00+00:00 [running]> on host 6fd0ba274d58
[2022-04-29 02:36:52,775] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-29 02:36:52,991] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=format_xl_to_csv_task
AIRFLOW_CTX_EXECUTION_DATE=2005-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2005-01-01T00:00:00+00:00
[2022-04-29 02:36:58,832] {python.py:175} INFO - Done. Returned value was: None
[2022-04-29 02:36:58,967] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=format_xl_to_csv_task, execution_date=20050101T000000, start_date=20220429T023651, end_date=20220429T023658
[2022-04-29 02:36:59,075] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-29 02:36:59,352] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-05-02 07:55:29,418] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__2005-01-01T00:00:00+00:00 [queued]>
[2022-05-02 07:55:29,459] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__2005-01-01T00:00:00+00:00 [queued]>
[2022-05-02 07:55:29,460] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 07:55:29,462] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 07:55:29,463] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 07:55:29,506] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_xl_to_csv_task> on 2005-01-01 00:00:00+00:00
[2022-05-02 07:55:29,515] {standard_task_runner.py:52} INFO - Started process 9428 to run task
[2022-05-02 07:55:29,523] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'format_xl_to_csv_task', 'scheduled__2005-01-01T00:00:00+00:00', '--job-id', '867', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpllnevg55', '--error-file', '/tmp/tmppg52lej5']
[2022-05-02 07:55:29,526] {standard_task_runner.py:77} INFO - Job 867: Subtask format_xl_to_csv_task
[2022-05-02 07:55:29,881] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__2005-01-01T00:00:00+00:00 [running]> on host ae42322ae538
[2022-05-02 07:55:30,116] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 07:55:30,295] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=format_xl_to_csv_task
AIRFLOW_CTX_EXECUTION_DATE=2005-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2005-01-01T00:00:00+00:00
[2022-05-02 07:55:36,291] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 07:55:36,452] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=format_xl_to_csv_task, execution_date=20050101T000000, start_date=20220502T075529, end_date=20220502T075536
[2022-05-02 07:55:36,578] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 07:55:36,979] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-05-02 09:17:35,639] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__2005-01-01T00:00:00+00:00 [queued]>
[2022-05-02 09:17:35,681] {taskinstance.py:1032} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__2005-01-01T00:00:00+00:00 [queued]>
[2022-05-02 09:17:35,683] {taskinstance.py:1238} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 09:17:35,684] {taskinstance.py:1239} INFO - Starting attempt 1 of 2
[2022-05-02 09:17:35,686] {taskinstance.py:1240} INFO - 
--------------------------------------------------------------------------------
[2022-05-02 09:17:35,731] {taskinstance.py:1259} INFO - Executing <Task(PythonOperator): format_xl_to_csv_task> on 2005-01-01 00:00:00+00:00
[2022-05-02 09:17:35,741] {standard_task_runner.py:52} INFO - Started process 2702 to run task
[2022-05-02 09:17:35,748] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'format_xl_to_csv_task', 'scheduled__2005-01-01T00:00:00+00:00', '--job-id', '986', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmp35ty7_jb', '--error-file', '/tmp/tmp7ar62qld']
[2022-05-02 09:17:35,750] {standard_task_runner.py:77} INFO - Job 986: Subtask format_xl_to_csv_task
[2022-05-02 09:17:36,112] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.format_xl_to_csv_task scheduled__2005-01-01T00:00:00+00:00 [running]> on host 98c324cf1bb6
[2022-05-02 09:17:36,352] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:152 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-05-02 09:17:36,535] {taskinstance.py:1426} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=format_xl_to_csv_task
AIRFLOW_CTX_EXECUTION_DATE=2005-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2005-01-01T00:00:00+00:00
[2022-05-02 09:17:42,076] {python.py:175} INFO - Done. Returned value was: None
[2022-05-02 09:17:42,186] {taskinstance.py:1277} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=format_xl_to_csv_task, execution_date=20050101T000000, start_date=20220502T091735, end_date=20220502T091742
[2022-05-02 09:17:42,285] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-05-02 09:17:42,504] {local_task_job.py:264} INFO - 1 downstream tasks scheduled from follow-on schedule check
