[2022-04-25 07:21:06,845] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.rm_files_task scheduled__1997-01-01T00:00:00+00:00 [queued]>
[2022-04-25 07:21:06,885] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.rm_files_task scheduled__1997-01-01T00:00:00+00:00 [queued]>
[2022-04-25 07:21:06,886] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 07:21:06,887] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-25 07:21:06,888] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-25 07:21:06,928] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): rm_files_task> on 1997-01-01 00:00:00+00:00
[2022-04-25 07:21:06,938] {standard_task_runner.py:52} INFO - Started process 2599 to run task
[2022-04-25 07:21:06,945] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'rm_files_task', 'scheduled__1997-01-01T00:00:00+00:00', '--job-id', '333', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmp8w_ycgt7', '--error-file', '/tmp/tmpb7i8l0f9']
[2022-04-25 07:21:06,948] {standard_task_runner.py:80} INFO - Job 333: Subtask rm_files_task
[2022-04-25 07:21:07,304] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.rm_files_task scheduled__1997-01-01T00:00:00+00:00 [running]> on host 64c7187bd08f
[2022-04-25 07:21:07,639] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-25 07:21:07,872] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=rm_files_task
AIRFLOW_CTX_EXECUTION_DATE=1997-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__1997-01-01T00:00:00+00:00
[2022-04-25 07:21:07,877] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-04-25 07:21:07,879] {subprocess.py:74} INFO - Running command: ['bash', '-c', "rm /opt/***//laucnty97.xlsx /opt/***/us_employment_{ execution_date.strftime('%y') }.parquet"]
[2022-04-25 07:21:07,896] {subprocess.py:85} INFO - Output:
[2022-04-25 07:21:07,933] {subprocess.py:89} INFO - bash: -c: line 0: syntax error near unexpected token `('
[2022-04-25 07:21:07,935] {subprocess.py:89} INFO - bash: -c: line 0: `rm /opt/***//laucnty97.xlsx /opt/***/us_employment_{ execution_date.strftime('%y') }.parquet'
[2022-04-25 07:21:07,936] {subprocess.py:93} INFO - Command exited with return code 1
[2022-04-25 07:21:08,037] {taskinstance.py:1774} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 188, in execute
    f'Bash command failed. The command returned a non-zero exit code {result.exit_code}.'
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2022-04-25 07:21:08,067] {taskinstance.py:1288} INFO - Marking task as UP_FOR_RETRY. dag_id=data_ingestion_gcp_dag, task_id=rm_files_task, execution_date=19970101T000000, start_date=20220425T072106, end_date=20220425T072108
[2022-04-25 07:21:08,123] {standard_task_runner.py:98} ERROR - Failed to execute job 333 for task rm_files_task (Bash command failed. The command returned a non-zero exit code 1.; 2599)
[2022-04-25 07:21:08,141] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-04-25 07:21:08,357] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-28 06:03:46,282] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.rm_files_task scheduled__1997-01-01T00:00:00+00:00 [queued]>
[2022-04-28 06:03:46,329] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.rm_files_task scheduled__1997-01-01T00:00:00+00:00 [queued]>
[2022-04-28 06:03:46,332] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 06:03:46,334] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-28 06:03:46,335] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-28 06:03:46,383] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): rm_files_task> on 1997-01-01 00:00:00+00:00
[2022-04-28 06:03:46,393] {standard_task_runner.py:52} INFO - Started process 1449 to run task
[2022-04-28 06:03:46,401] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'rm_files_task', 'scheduled__1997-01-01T00:00:00+00:00', '--job-id', '511', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmpa0cg_q57', '--error-file', '/tmp/tmpaqujfu57']
[2022-04-28 06:03:46,404] {standard_task_runner.py:80} INFO - Job 511: Subtask rm_files_task
[2022-04-28 06:03:46,752] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.rm_files_task scheduled__1997-01-01T00:00:00+00:00 [running]> on host d4721d223bdd
[2022-04-28 06:03:46,986] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-28 06:03:47,165] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=rm_files_task
AIRFLOW_CTX_EXECUTION_DATE=1997-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__1997-01-01T00:00:00+00:00
[2022-04-28 06:03:47,170] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-04-28 06:03:47,172] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'rm /opt/***/laucnty97.xlsx /opt/***/us_employment_97.parquet']
[2022-04-28 06:03:47,187] {subprocess.py:85} INFO - Output:
[2022-04-28 06:03:47,251] {subprocess.py:93} INFO - Command exited with return code 0
[2022-04-28 06:03:47,441] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=rm_files_task, execution_date=19970101T000000, start_date=20220428T060346, end_date=20220428T060347
[2022-04-28 06:03:47,512] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-28 06:03:47,720] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2022-04-29 02:33:41,100] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.rm_files_task scheduled__1997-01-01T00:00:00+00:00 [queued]>
[2022-04-29 02:33:41,142] {taskinstance.py:1043} INFO - Dependencies all met for <TaskInstance: data_ingestion_gcp_dag.rm_files_task scheduled__1997-01-01T00:00:00+00:00 [queued]>
[2022-04-29 02:33:41,144] {taskinstance.py:1249} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 02:33:41,145] {taskinstance.py:1250} INFO - Starting attempt 1 of 2
[2022-04-29 02:33:41,146] {taskinstance.py:1251} INFO - 
--------------------------------------------------------------------------------
[2022-04-29 02:33:41,187] {taskinstance.py:1270} INFO - Executing <Task(BashOperator): rm_files_task> on 1997-01-01 00:00:00+00:00
[2022-04-29 02:33:41,202] {standard_task_runner.py:52} INFO - Started process 5002 to run task
[2022-04-29 02:33:41,212] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'data_ingestion_gcp_dag', 'rm_files_task', 'scheduled__1997-01-01T00:00:00+00:00', '--job-id', '691', '--raw', '--subdir', 'DAGS_FOLDER/ingest_to_gcs_dag.py', '--cfg-path', '/tmp/tmp99t9mujv', '--error-file', '/tmp/tmpuxx7rswn']
[2022-04-29 02:33:41,215] {standard_task_runner.py:80} INFO - Job 691: Subtask rm_files_task
[2022-04-29 02:33:41,571] {logging_mixin.py:109} INFO - Running <TaskInstance: data_ingestion_gcp_dag.rm_files_task scheduled__1997-01-01T00:00:00+00:00 [running]> on host 6fd0ba274d58
[2022-04-29 02:33:41,811] {logging_mixin.py:109} WARNING - /home/***/.local/lib/python3.7/site-packages/***/utils/context.py:156 AirflowContextDeprecationWarning: Accessing 'execution_date' from the template is deprecated and will be removed in a future version. Please use 'data_interval_start' or 'logical_date' instead.
[2022-04-29 02:33:41,988] {taskinstance.py:1448} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=data_ingestion_gcp_dag
AIRFLOW_CTX_TASK_ID=rm_files_task
AIRFLOW_CTX_EXECUTION_DATE=1997-01-01T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__1997-01-01T00:00:00+00:00
[2022-04-29 02:33:41,996] {subprocess.py:62} INFO - Tmp dir root location: 
 /tmp
[2022-04-29 02:33:42,000] {subprocess.py:74} INFO - Running command: ['bash', '-c', 'rm /opt/***/laucnty97.xlsx /opt/***/us_employment_1997.parquet']
[2022-04-29 02:33:42,034] {subprocess.py:85} INFO - Output:
[2022-04-29 02:33:42,096] {subprocess.py:93} INFO - Command exited with return code 0
[2022-04-29 02:33:42,291] {taskinstance.py:1288} INFO - Marking task as SUCCESS. dag_id=data_ingestion_gcp_dag, task_id=rm_files_task, execution_date=19970101T000000, start_date=20220429T023341, end_date=20220429T023342
[2022-04-29 02:33:42,373] {local_task_job.py:154} INFO - Task exited with return code 0
[2022-04-29 02:33:42,583] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
